paises_permitidos:
- Brazil

limite_tentativas_login: 5

email_alertas:
  remetente: "remetente@gmail.com"
  senha: "sua_senha_do_email" 
  destinatario: "destinatario@email.com"
  smtp: "smtp.gmail.com"
  porta: 587
